---
- hosts: localhost
  tasks:
    - name: installing repo for Java 8 in Ubuntu
      apt_repository: repo='ppa:webupd8team/java' update-cache=yes
    - name: config java
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
    - name: Install Java
      package: name='oracle-java8-installer' state=latest
    - name: set java home
      lineinfile: dest=/etc/profile line='export JAVA_HOME=/usr/lib/jvm/java-8-oracle' insertafter='EOF'
    - shell: . /etc/profile executable=/bin/bash 

    - name: Download maven
      get_url: url=https://archive.apache.org/dist/maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.tar.gz dest=/usr/local
    - name: extract maven
      shell: chdir=/usr/local tar -zxf apache-maven-3.1.1-bin.tar.gz
    - name: export maven
      shell: export PATH=/usr/local/apache-maven-3.1.1/bin:$PATH
    - name: config maven home
      lineinfile: dest=/etc/profile line='export M2_HOME=/usr/local/apache-maven-3.1.1' insertafter='EOF'
    - file: src=/usr/local/apache-maven-3.1.1/bin/mvn dest=/usr/bin/mvn state=link
    - name: export maven
      shell: export PATH=/usr/local/apache-maven-3.1.1/bin:$PATH

    - name: Clone petclinic repo
      git: repo=https://github.com/savishy/spring-petclinic dest=/opt/test
    - name: build project
      shell: mvn clean package chdir=/opt/test 

    - name: run project
      shell: nohup java -jar *jar & chdir=/opt/test/target
