---
- hosts: localhost
  tasks:
    - name: installing repo for Java 8 in Ubuntu
      apt_repository: repo='ppa:webupd8team/java' update-cache=yes
    - name: config java
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
    - name: Install Java
      package: name='oracle-java8-installer' state=latest
    - name: set java home
      lineinfile: dest=/etc/profile line='export JAVA_HOME=/usr/local' insertafter='EOF'
    - shell: source "/etc/profile" && echo $JAVA_HOME
      register: test
    - debug: var=test.stdout

      
